import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;

public class Payment_Info extends javax.swing.JFrame 
{
    int Price;
    Show S;
    
    public Payment_Info() 
    {
        initComponents();
    }
    
    public Payment_Info(int MovieIndex,int TheaterIndex,int ShowIndex,int Num_Tickets) {
        initComponents();
        Move_Name.setText(City.Movies.get(MovieIndex).getMovie_Name());
        Theatre_Name.setText(City.Movies.get(MovieIndex).getTheaters().get(TheaterIndex).getTheater_Name());
        Time.setText(City.Movies.get(MovieIndex).getTheaters().get(TheaterIndex).getShows().get(ShowIndex).getTime());
        Type.setText(City.Movies.get(MovieIndex).getTheaters().get(TheaterIndex).getShows().get(ShowIndex).getType());
        username.setText(Login.Current_Customer.getUsername());
        switch (City.Movies.get(MovieIndex).getTheaters().get(TheaterIndex).getShows().get(ShowIndex).getType()) {
            case "Regular":
                Price=City.Movies.get(MovieIndex).getTheaters().get(TheaterIndex).getRegular_Price()*Num_Tickets;
                jLabel5.setText(String.valueOf(Price) + "LE");
                break;
            case "3D":
                Price=City.Movies.get(MovieIndex).getTheaters().get(TheaterIndex).getThreeDim_Price()*Num_Tickets;
                jLabel5.setText(String.valueOf(Price) + "LE");
                break;
            case "4D":
                Price=City.Movies.get(MovieIndex).getTheaters().get(TheaterIndex).getFourDim_Price()*Num_Tickets;
                jLabel5.setText(String.valueOf(Price) + "LE");
                break;
        }
    }
    
    public void Save(Payment e)
    {
        try {
            List<Payment> p = Login.customers.get(Login.CurrentCustomerIndex).getPayments();
            p.add(e);
            Login.customers.get(Login.CurrentCustomerIndex).setPayments(p);
            Customer.SaveCustomers(Login.customers);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Payment_Info.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Payment_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Card_Num = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Card_Holder = new javax.swing.JTextField();
        Card_Type = new javax.swing.JComboBox();
        Time = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Move_Name = new javax.swing.JLabel();
        Theatre_Name = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Card_Num.setForeground(new java.awt.Color(153, 0, 51));
        jPanel1.add(Card_Num);
        Card_Num.setBounds(288, 192, 240, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(48, 96, 72, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Card Number");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(132, 192, 120, 28);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/done.png"))); // NOI18N
        jButton1.setText("Done");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 320, 132, 36);

        Card_Holder.setForeground(new java.awt.Color(153, 0, 51));
        Card_Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card_HolderActionPerformed(evt);
            }
        });
        jPanel1.add(Card_Holder);
        Card_Holder.setBounds(288, 240, 240, 28);

        Card_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debit Card", "Credit Card" }));
        Card_Type.setSelectedItem("Select Card Type");
        jPanel1.add(Card_Type);
        Card_Type.setBounds(288, 144, 240, 28);

        Time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Time");
        jPanel1.add(Time);
        Time.setBounds(132, 36, 72, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Card Holder Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(132, 240, 132, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(132, 96, 60, 17);

        Type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setText("Type");
        jPanel1.add(Type);
        Type.setBounds(48, 36, 84, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Card Type");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(132, 144, 96, 24);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 792, 420);

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Movie Ticket Booking System");

        Move_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Move_Name.setText("Movie Name");

        Theatre_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Theatre_Name.setText("Theatre Name");

        username.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_username_login_1172613.png"))); // NOI18N
        username.setText("Username");

        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-64.png"))); // NOI18N
        exit.setText("Exit");
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Move_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Theatre_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(33, 33, 33)
                        .addComponent(username))
                    .addComponent(exit))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Theatre_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Move_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!Card_Num.getText().equals("") && !Card_Holder.getText().equals(""))
        {              
        if(Login.Current_Customer.getCard_Number().equals(Card_Num.getText()))
        {
            try {
                Payment e = new Payment(Price,Card_Type.getSelectedItem().toString(),Card_Holder.getText(),Move_Name.getText(),Theatre_Name.getText());
                Save(e);
                JOptionPane.showMessageDialog(rootPane, "Successful Payment","Done",JOptionPane.INFORMATION_MESSAGE);
                int option = JOptionPane.OK_CANCEL_OPTION;
                int result = JOptionPane.showConfirmDialog(rootPane, "Do you want to Book another ticket?","",option);
                if (result == JOptionPane.OK_OPTION)
                {
                City Form=new City();
                this.hide();
                Form.setVisible(true);
                }
                else
                    exitActionPerformed(evt);
                
            } catch (ParserConfigurationException ex) {
                Logger.getLogger(Payment_Info.class.getName()).log(Level.SEVERE, null, ex);
            } catch (TransformerException ex) {
                Logger.getLogger(Payment_Info.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "Check Card Number","Error",JOptionPane.INFORMATION_MESSAGE);
           }
        }
        else if(Card_Num.getText().equals("") || Card_Holder.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Fill all details","Error",JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Card_HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card_HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Card_HolderActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Payment_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Card_Holder;
    private javax.swing.JTextField Card_Num;
    private javax.swing.JComboBox Card_Type;
    private javax.swing.JLabel Move_Name;
    private javax.swing.JLabel Theatre_Name;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Type;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
